"""added due_date, notification model, term and year to payment

Revision ID: 3f9dd1280892
Revises: 6b2107f20ad0
Create Date: 2026-06-11 23:38:53.911521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f9dd1280892'
down_revision = '6b2107f20ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    op.drop_table('expenses')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('receipt_number'))

    op.drop_table('receipts')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('term')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('notification_type')
        batch_op.drop_column('title')

    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    op.create_table('receipts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('receipt_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('issue_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('receipts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('receipt_number'), ['receipt_number'], unique=True)

    op.create_table('expenses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analytics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('metric_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('metric_value', mysql.FLOAT(), nullable=False),
    sa.Column('recorded_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
