"""initial

Revision ID: 91c1b2fbc294
Revises: 3f9dd1280892
Create Date: 2026-06-14 20:37:05.994761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c1b2fbc294'
down_revision = '3f9dd1280892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('mpesa_code')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('mpesa_requests', schema=None) as batch_op:
        batch_op.drop_column('result_code')

    # ### end Alembic commands ###
